utils/audit.py:get_redacted_data: check that data is defined (#1098)
otherwise (at lease heartbeat delete) can fail with:
File "alerta/utils/audit.py", line 86, in get_redacted_data
if 'password' in data:
TypeError: argument of type 'NoneType' is not iterable